#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  6 09:51:12 2022

@author: amanda
"""

# 基础数据科学运算库
import numpy as np
import pandas as pd
from numpy.random import RandomState

# 可视化库
import seaborn as sns
import matplotlib.pyplot as plt

# sklearn库
# 数据预处理
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

# 实用函数
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# 常用评估器
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_val_score

# 网格搜索
from sklearn.model_selection import GridSearchCV

# 自定义评估器支持模块
from sklearn.base import BaseEstimator, TransformerMixin, ClassifierMixin

# 其他辅助模块
import inspect, re
from tqdm import tqdm
import gc
import time
from joblib import dump, load
import warnings
warnings.filterwarnings('ignore')

# hyperopt优化器
from hyperopt import hp, fmin, tpe

